// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ddd_project.Infrastructure.ORM;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ColcicExtensaoContext))]
    partial class ColcicExtensaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ddd_project.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("ddd_project.Domain.AlunoAtividade", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AtividadeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ch")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "AtividadeId");

                    b.HasIndex("AtividadeId");

                    b.ToTable("AlunosAtividades", (string)null);
                });

            modelBuilder.Entity("ddd_project.Domain.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Atividades", (string)null);
                });

            modelBuilder.Entity("ddd_project.Domain.AlunoAtividade", b =>
                {
                    b.HasOne("ddd_project.Domain.Aluno", "Aluno")
                        .WithMany("AlunoAtividades")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ddd_project.Domain.Atividade", "Atividade")
                        .WithMany("AlunoAtividades")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ddd_project.Domain.Aluno", b =>
                {
                    b.Navigation("AlunoAtividades");
                });

            modelBuilder.Entity("ddd_project.Domain.Atividade", b =>
                {
                    b.Navigation("AlunoAtividades");
                });
#pragma warning restore 612, 618
        }
    }
}
